---
apiVersion: apps/v1
kind: Deploymenthttps://github.com/Ashok-M-7702/mindcircuit13/blob/main/deploymentfiles/deployment.yml
metadata:
  name: pythonapp
  labels:
    app: pythonapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: chary7702/batch13:tomcatimage
        ports:
        - containerPort: 8080
